apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: newpod
  name: newpod
spec:
  containers:
  - image: justamitsaha/case-study-three
    name: newpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}